[build]
  publish = "."

[[redirects]]
  from = "/*"
  # 直接代理到域名（证书已绑定该域名），而非IP
  to = "https://zby.130519.xyz/:splat"
  status = 200
  force = true
  # 无需再手动设置Host头，因为目标地址已包含域名
  # [redirects.headers]
  #   Host = "zby.130519.xyz"
